---
title: "A machine learnig algorithm for activity recognition"
author: "Stefano Galeano"
date: "9/14/2017"
output:
  pdf_document: default
  html_document: default
references:
- URL: http://groupware.les.inf.puc-rio.br/work.jsf?p1=11201
  author:
  - family: Velloso
    given: Eduardo
  id: velloso2013
  issued:
    year: 2013
  publisher: Proceedings of 4th International Conference in Cooperation with SIGCHI
    (Augmented Human '13)
  title: Qualitative Activity Recognition of Weight Lifting Exercises
  type: article-journal
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# PML - Final assignment

## Introduction

## Getting and cleaning data

```{r, message=TRUE, warning=TRUE, cache=TRUE}
trainUrl <- 'https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv'
testUrl <- 'https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv'

download.file(url = trainUrl,destfile = 'data/train.csv')
download.file(url = testUrl,destfile = 'data/test.csv')
train <- read.csv('data/train.csv', header = TRUE,
                  stringsAsFactors = FALSE, na.strings = c("NA","#DIV/0!",""))
test <- read.csv('data/test.csv', header = TRUE,
                 stringsAsFactors = FALSE, na.strings = c("NA","#DIV/0!",""))
```

```{r}
library(caret)

rawFeatures <- grep(pattern = "^(accel|gyros|magnet)_.*_(x|y|z)$",x = names(train))
rawFeatures <- c(rawFeatures,grep(pattern = "^(roll|pitch|yaw)_.*",x = names(train)))
rawFeatures <- c(rawFeatures,grep(pattern = "^total_accel.*",x = names(train)))

ds.sel <- train[,rawFeatures]
ds.sel$classe <- as.factor(train$classe)
```

```{r}
inTrain <- createDataPartition(ds.sel$classe,p=.75,list = FALSE)

train.sel <- ds.sel[inTrain,]
test.sel <- ds.sel[-inTrain,]
```

```{r}
rawFeatures <- grep(pattern = "^(accel|gyros|magnet)_.*_(x|y|z)$",x = names(test))
rawFeatures <- c(rawFeatures,grep(pattern = "^(roll|pitch|yaw)_.*",x = names(test)))
rawFeatures <- c(rawFeatures,grep(pattern = "^total_accel.*",x = names(test)))
quiz.sel <- test[,rawFeatures]
```

## Exploratory data analysis


```{r}
outcomeIndex <- which(names(train.sel) == "classe")
train.cor <- cor(train.sel[,-outcomeIndex])
highlyCorrelated <- findCorrelation(train.cor, cutoff=0.75, names = TRUE)
train.sel[,highlyCorrelated] <- NULL
```

```{r cache=TRUE}
library(parallel)
library(doParallel)
cluster <- makeCluster(detectCores() - 1) # convention to leave 1 core for OS
registerDoParallel(cluster)

control <- trainControl(method="cv", number=10,allowParallel = TRUE)
model <- train(classe~., data=train.sel, method="rf", trControl=control)
stopCluster(cluster)
registerDoSEQ()
```

```{r}
importance <- varImp(model, scale=FALSE)
ord <- order(importance$importance,decreasing = TRUE)

plot(importance)
```

```{r cache=TRUE}
cluster <- makeCluster(detectCores() - 1) # convention to leave 1 core for OS
registerDoParallel(cluster)

control <- trainControl(method="none",allowParallel = TRUE)
models <- lapply(2:length(ord),function(i){
        df <- train.sel[,ord[1:i]]
        df$classe <- train.sel$classe
        train(classe~., data=df, method="rf", trControl=control)      
})

stopCluster(cluster)
registerDoSEQ()
```
```{r}
accuracies <- sapply(1:length(models), function(i){
        df <- models[[i]]$finalModel
        cf <- confusionMatrix(data = df$pred, reference = df$y)
        cf$overall["Accuracy"]

})
```
```{r}
data <- data.frame(paramCount = 1:length(accuracies), acc = accuracies)
g <- ggplot(data,mapping = aes(x=paramCount,y=acc))
# g <- g + ylim(0.7, 1)
g <- g + geom_linerange(aes(ymin=.7,ymax=1))
g <- g + xlab("# of predictors")
g <- g + ylab("Accuracy (in sample error)")
g
```
```{r}
pred <- predict(model,newdata = test.sel)
pred
```
## Conclusion
